### ISSUE TITLE
Add some urls of this gem

### ISSUE THREAD

**Issue by JuanitoFatas** [github/task_list#54]
Hello maintainer,

Could you please add these information on rubygems.org?

![screenshot 2015-02-24 20 31 50](https://cloud.githubusercontent.com/assets/1000669/6349316/31782444-bc64-11e4-87b8-3d2312bd14b5.png)

Here are some I know:

| URL                   | VALUE                                      |
| --------------------- | ------------------------------------------ |
| **Source Code URL**   | https://github.com/github/task_list        |
| **Documentation URL** | http://www.rubydoc.info/gems/task_list     |
| **Wiki URL**          | N/A                                        |
| **Mailing List URL**  | N/A                                        |
| **Bug Tracker URL**   | https://github.com/github/task_list/issues |

Thanks!

**Comment by mtodd** [comment]
@JuanitoFatas done! Thanks for the reminder (thought I'd done this before)!
