### ISSUE TITLE
Enable task to be related to issue

### ISSUE THREAD

**Issue by bjornharrtell** [github/task_list#63]
I like the task list. It would be even nicer if it was somehow possible to refer a task to an issue and have the checked attribute be directly derived from the open/closed status of the issue,

**Comment by bkeepers** [comment]
Hi @bjornharrtell, thanks for the feature request! I know this is on the radar of the team that manages GitHub Issues. There's not really anything that can be changed in this library to make that feature happen, so I'm going to close this issue.
